[package]
categories = ["embedded", "no-std", "hardware-support", "network-programming"]
name = "stm32-eth"
description = "Embedded Rust Ethernet driver for the STM32 MCU series"
license = "Apache-2.0"
authors = ["Astro <astro@spaceboyz.net>"]
version = "0.3.0"
keywords = ["ethernet", "eth", "stm32", "stm32f4", "stm32f7"]
repository = "https://github.com/stm32-rs/stm32-eth"
documentation = "https://docs.rs/stm32-eth/"
edition = "2018"

[badges]
travis-ci = { repository = "astro/stm32-eth", branch = "master" }
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
features = ["smoltcp-phy", "smoltcp/socket-raw", "stm32f429"]

[dependencies]
volatile-register = "0.2"
aligned = "0.4"
stm32f7xx-hal = { version = "0.7.0", optional = true }
stm32f4xx-hal = { version = "0.13", optional = true }
stm32f1xx-hal = { git = "https://github.com/datdenkikniet/stm32f1xx-hal.git", branch = "gd32f107", optional = true }
# stm32f1xx-hal = { path = "../stm32f1xx-hal", optional = true }
ieee802_3_miim = { version = "0.7", optional = true }
cortex-m = "0.7"
log = { version = "0.4", optional = true }
defmt = { version = "0.3", optional = true }

# For rtic-echo
cortex-m-rtic = { version = "1.0", optional = true }
defmt-rtt = { version = "0.3", optional = true }
panic-probe = { version = "0.3", optional = true, features = [ "print-defmt" ] }
systick-monotonic = { version = "1.0", optional = true }
fugit = { version = "0.3", optional = true}

[dependencies.smoltcp]
git = "https://github.com/datdenkikniet/smoltcp.git"
branch = "unique_packet_id"
default-features = false
features = ["medium-ethernet", "proto-ipv4"]
optional = true

[features]
default = [ "ieee802_3_miim", "defmt" ]
device-selected = []
fence = []

stm32f107 = ["stm32f1xx-hal/stm32f107", "device-selected"]

stm32f407 = ["stm32f4xx-hal/stm32f407", "device-selected"]
stm32f417 = ["stm32f4xx-hal/stm32f417", "device-selected"]
stm32f427 = ["stm32f4xx-hal/stm32f427", "device-selected"]
stm32f429 = ["stm32f4xx-hal/stm32f429", "device-selected"]
stm32f437 = ["stm32f4xx-hal/stm32f437", "device-selected"]
stm32f439 = ["stm32f4xx-hal/stm32f439", "device-selected"]
stm32f469 = ["stm32f4xx-hal/stm32f469", "device-selected"]
stm32f479 = ["stm32f4xx-hal/stm32f479", "device-selected"]

stm32f745 = ["stm32f7xx-hal/stm32f745", "device-selected", "fence"]
stm32f746 = ["stm32f7xx-hal/stm32f746", "device-selected", "fence"]
stm32f756 = ["stm32f7xx-hal/stm32f756", "device-selected", "fence"]
stm32f765 = ["stm32f7xx-hal/stm32f765", "device-selected", "fence"]
stm32f767 = ["stm32f7xx-hal/stm32f767", "device-selected", "fence"]
stm32f769 = ["stm32f7xx-hal/stm32f769", "device-selected", "fence"]
stm32f777 = ["stm32f7xx-hal/stm32f777", "device-selected", "fence"]
stm32f778 = ["stm32f7xx-hal/stm32f778", "device-selected", "fence"]
stm32f779 = ["stm32f7xx-hal/stm32f779", "device-selected", "fence"]

smoltcp-phy = ["smoltcp"]

# Example features
rtic-echo-example = [ "ieee802_3_miim", "cortex-m-rtic", "smoltcp-phy", "smoltcp/defmt", "smoltcp/medium-ethernet", "smoltcp/socket-tcp", "defmt", "defmt-rtt", "panic-probe", "systick-monotonic", "fugit" ]
rtic-echo-example-altpin = [ ]

[dev-dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-itm = "0.4"
cortex-m-semihosting = "0.3"
fugit = "0.3"

[[example]]
name = "pktgen"
required-features = ["stm32f429"]

[[example]]
name = "ip"
required-features = [
    "stm32f429", "smoltcp-phy", "log", "smoltcp/socket-tcp", "smoltcp/socket-icmp",
    "smoltcp/log", "smoltcp/verbose"
]

[[example]]
name = "ip-f107"
required-features = [
    "stm32f107", "smoltcp-phy", "log", "smoltcp/socket-tcp", "smoltcp/socket-icmp",
    "smoltcp/log", "smoltcp/verbose"
]

[[example]]
name = "arp"
required-features = ["stm32f407"]

[[example]]
name = "arp-smoltcp"
required-features = ["stm32f407", "smoltcp-phy", "smoltcp/socket-icmp"]

[[example]]
name = "rtic-echo"
required-features = [ "rtic-echo-example" ]

[profile.release]
debug = 2
lto = true
